// <auto-generated />
using System;
using ExamenPGG.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenPGG.Data.Migrations
{
    [DbContext(typeof(GameOfBatsContext))]
    partial class GameOfBatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("ExamenPGG.Data.Entities.DBGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThrowsToWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WinnerID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ExamenPGG.Data.Entities.DBPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DBGameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("DBGameID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ExamenPGG.Data.Entities.DBGame", b =>
                {
                    b.HasOne("ExamenPGG.Data.Entities.DBPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("WinnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ExamenPGG.Data.Entities.DBPlayer", b =>
                {
                    b.HasOne("ExamenPGG.Data.Entities.DBGame", null)
                        .WithMany("PlayerList")
                        .HasForeignKey("DBGameID");
                });

            modelBuilder.Entity("ExamenPGG.Data.Entities.DBGame", b =>
                {
                    b.Navigation("PlayerList");
                });
#pragma warning restore 612, 618
        }
    }
}
